name: "tagged-release"

on:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: assemble
      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: artifacts
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: jar
          path: |
            app/build/libs/app-all.jar
            
      - name: "Build & test"
        run: |
          echo "done!"
          
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            LICENSE
            app/build/libs/app-all.jar
